PUT http://localhost:3001/api/notes/644948c084c6a4480099e3cf
Content-Type: application/json

{
  "content": "render +++++",
  "important": true
}


###

GET http://localhost:3001/api/notes/2
Accept: application/json


###
POST http://localhost:3001/api/notes
Content-Type: application/json

{
  "content": "render",
  "important": false
}
###

GET http://localhost:3001/api/notes
Accept: application/json

###
DELETE http://localhost:3001/api/notes/644ce93c74aacd52137b8a6d
Accept: application/json

###
http://localhost:3001/api/notes/